### PR TITLE
Added Swift badge

### PR DESCRIPTION
**Pull request by lfarah**

### CODE REVIEW

**Comment by johnlui** [comment]
Dose there be some way to update swift badge to the latest version?

**Comment by lfarah** [comment]
@johnlui It's all about changing the version on the url:
[Language](http://swift.org)
[Language](http://swift.org)
[Language](http://swift.org)

**Comment by johnlui** [comment]
I do not want to update the tiny version after the point...

**Comment by lfarah** [comment]
You can also update the major version:
[Language](http://swift.org)
[Language](http://swift.org)
[Language](http://swift.org)

**Comment by johnlui** [comment]
Haha, I found that the you can put any word at 2.1 position.

https://img.shields.io/badge/swift-latest-orange.svg
[Swift](https://img.shields.io/badge/swift-latest-orange.svg)

**Pull request closed without merging**
